blog/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views
import monde.urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^', include(monde.urls)),
]

monde/urls.py
from django.conf.urls import url

from .views import EntryDetail

urlpatterns = [
    url(r'^(?P<pk>\d+)/$', EntryDetail.as_view(), name='entry_detail'),
]

monde/models.py
from django.db import models


class Entry(models.Model):

    class Meta:
        verbose_name_plural = "entries"

    title = models.CharField(max_length=500)
    author = models.ForeignKey('auth.User')
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    modified_at = models.DateTimeField(auto_now=True, editable=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('entry_detail', kwargs={'pk': self.pk})


class Comment(models.Model):
    entry = models.ForeignKey(Entry)
    name = models.CharField(max_length=100)
    email = models.EmailField()
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    modified_at = models.DateTimeField(auto_now=True, editable=False)

    def __str__(self):
        return self.body

monde/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

    def __init__(self, *args, **kwargs):
        self.entry = kwargs.pop('entry')
        super().__init__(*args, **kwargs)

    def save(self):
        comment = super().save(commit=False)
        comment.entry = self.entry
        comment.save()
        return comment

blog/views.py
from django.views.generic import ListView
from monde.models import Entry


class HomeView(ListView):
    template_name = 'index.html'
    queryset = Entry.objects.order_by('-created_at')

monde/views.py
from django.shortcuts import get_object_or_404
from django.views.generic import CreateView

from .forms import CommentForm
from .models import Entry


class EntryDetail(CreateView):
    model = Entry
    template_name = 'monde/entry_detail.html'
    form_class = CommentForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['entry'] = self.get_object()
        return kwargs

    def get_context_data(self, **kwargs):
        d = super().get_context_data(**kwargs)
        d['entry'] = self.get_object()
        return d

    def get_success_url(self):
        return self.get_object().get_absolute_url()

templates/_entry.html
<article>

    <h2><a href="{{ entry.get_absolute_url }}">{{ entry.title }}</a></h2>

    <p class="subheader">
        <time>{{ entry.modified_at|date }}</time>
    </p>


    {{ entry.body|linebreaks }}

</article>

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>Wraeclast</title>
    <link rel="stylesheet" href="{% static "css/foundation.css" %}">
</head>
<body>
    <section class="row">
        <header class="large-12 columns">
            <h1>Welcome to la fin de monde, exile</h1>
            <hr>
        </header>
    </section>

    <section class="row">

        <div class="large-8 columns">
            {% block content %}{% endblock %}
        </div>

        <div class="large-4 columns">
            {% block about %}{% endblock %}        
        </div>

    </section>

</body>
</html>

templates/index.html
{% extends "base.html" %}

{% block content %}
    {% for entry in entry_list %}
        {% include "_entry.html" with entry=entry only %}
    {% empty %}
        <p>No blog entries yet.</p>
    {% endfor %}
{% endblock content %}
{% block about %}
            <h3>About</h3>
            <p>Wraeclast: the land of the damned. This forsaken continent is home to many writhing horrors, murderous beasts, and ravenous undead. The very soil is permeated with dark, ancient power, the earth shivering with malice. The dead are refused peace, rising up and hopelessly wandering in eternal pain, sorrow and hunger. The wildlife is twisted and misshapen, unnaturally aggressive and savage. Lurking in the darkest of corners, unspeakable horrors lie in wait for unsuspecting prey, eager to rip apart the mind as well as the flesh. Wraeclast is a place where few remain alive, and fewer remain sane. </p> 
{% endblock about %}

 

templates/monde/entry_detail.html
{% extends "base.html" %}


{%block content%}

  {% include "_entry.html" with entry=entry only %}
    <h4>Comments</h4>
       {% for comment in entry.comment_set.all %}
          <p><em>Posted by {{ comment.name }}</em></p>
          {{ comment|linebreaks }}
          {% empty %}
           <p>No comments yet.</p>
       {% endfor %}

    <h5>Add a comment</h5>
    <form method="post">
        {% csrf_token %}
      {{ form.as_table }}
      <input type="submit" value="Create Comment">
    </form>

{%endblock content%}